// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    int32_t capacity;
    int32_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, const uint8_t *_Nonnull, int32_t, RustBuffer *_Nonnull);

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

// Continuation callback for UniFFI Futures
typedef void (*UniFfiRustFutureContinuation)(void * _Nonnull, int8_t);

// Scaffolding functions
void*_Nonnull uniffi_portal_fn_clone_debugmessage(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_portal_fn_free_debugmessage(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_portal_fn_clone_portalsdk(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_portal_fn_free_portalsdk(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_portal_fn_constructor_portalsdk_new(int8_t use_fast_ops, RustCallStatus *_Nonnull out_status
);
void* _Nonnull uniffi_portal_fn_method_portalsdk_debug_msg(void*_Nonnull ptr
);
void* _Nonnull uniffi_portal_fn_method_portalsdk_debug_send_raw(void*_Nonnull ptr, RustBuffer data
);
void* _Nonnull uniffi_portal_fn_method_portalsdk_debug_wipe_device(void*_Nonnull ptr
);
void* _Nonnull uniffi_portal_fn_method_portalsdk_display_address(void*_Nonnull ptr, uint32_t index
);
void* _Nonnull uniffi_portal_fn_method_portalsdk_generate_mnemonic(void*_Nonnull ptr, RustBuffer num_words, RustBuffer network, RustBuffer password
);
void* _Nonnull uniffi_portal_fn_method_portalsdk_get_status(void*_Nonnull ptr
);
void* _Nonnull uniffi_portal_fn_method_portalsdk_get_xpub(void*_Nonnull ptr, RustBuffer path
);
void* _Nonnull uniffi_portal_fn_method_portalsdk_incoming_data(void*_Nonnull ptr, uint64_t msg_index, RustBuffer data
);
void* _Nonnull uniffi_portal_fn_method_portalsdk_new_tag(void*_Nonnull ptr
);
void* _Nonnull uniffi_portal_fn_method_portalsdk_poll(void*_Nonnull ptr
);
void* _Nonnull uniffi_portal_fn_method_portalsdk_public_descriptors(void*_Nonnull ptr
);
void* _Nonnull uniffi_portal_fn_method_portalsdk_restore_mnemonic(void*_Nonnull ptr, RustBuffer mnemonic, RustBuffer network, RustBuffer password
);
void* _Nonnull uniffi_portal_fn_method_portalsdk_resume(void*_Nonnull ptr
);
void* _Nonnull uniffi_portal_fn_method_portalsdk_set_descriptor(void*_Nonnull ptr, RustBuffer descriptor, RustBuffer bsms
);
void* _Nonnull uniffi_portal_fn_method_portalsdk_sign_psbt(void*_Nonnull ptr, RustBuffer psbt
);
void* _Nonnull uniffi_portal_fn_method_portalsdk_unlock(void*_Nonnull ptr, RustBuffer password
);
void* _Nonnull uniffi_portal_fn_method_portalsdk_update_firmware(void*_Nonnull ptr, RustBuffer binary
);
RustBuffer ffi_portal_rustbuffer_alloc(int32_t size, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_portal_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
void ffi_portal_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_portal_rustbuffer_reserve(RustBuffer buf, int32_t additional, RustCallStatus *_Nonnull out_status
);
void ffi_portal_rust_future_poll_u8(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_portal_rust_future_cancel_u8(void* _Nonnull handle
);
void ffi_portal_rust_future_free_u8(void* _Nonnull handle
);
uint8_t ffi_portal_rust_future_complete_u8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_portal_rust_future_poll_i8(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_portal_rust_future_cancel_i8(void* _Nonnull handle
);
void ffi_portal_rust_future_free_i8(void* _Nonnull handle
);
int8_t ffi_portal_rust_future_complete_i8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_portal_rust_future_poll_u16(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_portal_rust_future_cancel_u16(void* _Nonnull handle
);
void ffi_portal_rust_future_free_u16(void* _Nonnull handle
);
uint16_t ffi_portal_rust_future_complete_u16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_portal_rust_future_poll_i16(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_portal_rust_future_cancel_i16(void* _Nonnull handle
);
void ffi_portal_rust_future_free_i16(void* _Nonnull handle
);
int16_t ffi_portal_rust_future_complete_i16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_portal_rust_future_poll_u32(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_portal_rust_future_cancel_u32(void* _Nonnull handle
);
void ffi_portal_rust_future_free_u32(void* _Nonnull handle
);
uint32_t ffi_portal_rust_future_complete_u32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_portal_rust_future_poll_i32(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_portal_rust_future_cancel_i32(void* _Nonnull handle
);
void ffi_portal_rust_future_free_i32(void* _Nonnull handle
);
int32_t ffi_portal_rust_future_complete_i32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_portal_rust_future_poll_u64(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_portal_rust_future_cancel_u64(void* _Nonnull handle
);
void ffi_portal_rust_future_free_u64(void* _Nonnull handle
);
uint64_t ffi_portal_rust_future_complete_u64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_portal_rust_future_poll_i64(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_portal_rust_future_cancel_i64(void* _Nonnull handle
);
void ffi_portal_rust_future_free_i64(void* _Nonnull handle
);
int64_t ffi_portal_rust_future_complete_i64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_portal_rust_future_poll_f32(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_portal_rust_future_cancel_f32(void* _Nonnull handle
);
void ffi_portal_rust_future_free_f32(void* _Nonnull handle
);
float ffi_portal_rust_future_complete_f32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_portal_rust_future_poll_f64(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_portal_rust_future_cancel_f64(void* _Nonnull handle
);
void ffi_portal_rust_future_free_f64(void* _Nonnull handle
);
double ffi_portal_rust_future_complete_f64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_portal_rust_future_poll_pointer(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_portal_rust_future_cancel_pointer(void* _Nonnull handle
);
void ffi_portal_rust_future_free_pointer(void* _Nonnull handle
);
void*_Nonnull ffi_portal_rust_future_complete_pointer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_portal_rust_future_poll_rust_buffer(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_portal_rust_future_cancel_rust_buffer(void* _Nonnull handle
);
void ffi_portal_rust_future_free_rust_buffer(void* _Nonnull handle
);
RustBuffer ffi_portal_rust_future_complete_rust_buffer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_portal_rust_future_poll_void(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_portal_rust_future_cancel_void(void* _Nonnull handle
);
void ffi_portal_rust_future_free_void(void* _Nonnull handle
);
void ffi_portal_rust_future_complete_void(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
uint16_t uniffi_portal_checksum_method_portalsdk_debug_msg(void
    
);
uint16_t uniffi_portal_checksum_method_portalsdk_debug_send_raw(void
    
);
uint16_t uniffi_portal_checksum_method_portalsdk_debug_wipe_device(void
    
);
uint16_t uniffi_portal_checksum_method_portalsdk_display_address(void
    
);
uint16_t uniffi_portal_checksum_method_portalsdk_generate_mnemonic(void
    
);
uint16_t uniffi_portal_checksum_method_portalsdk_get_status(void
    
);
uint16_t uniffi_portal_checksum_method_portalsdk_get_xpub(void
    
);
uint16_t uniffi_portal_checksum_method_portalsdk_incoming_data(void
    
);
uint16_t uniffi_portal_checksum_method_portalsdk_new_tag(void
    
);
uint16_t uniffi_portal_checksum_method_portalsdk_poll(void
    
);
uint16_t uniffi_portal_checksum_method_portalsdk_public_descriptors(void
    
);
uint16_t uniffi_portal_checksum_method_portalsdk_restore_mnemonic(void
    
);
uint16_t uniffi_portal_checksum_method_portalsdk_resume(void
    
);
uint16_t uniffi_portal_checksum_method_portalsdk_set_descriptor(void
    
);
uint16_t uniffi_portal_checksum_method_portalsdk_sign_psbt(void
    
);
uint16_t uniffi_portal_checksum_method_portalsdk_unlock(void
    
);
uint16_t uniffi_portal_checksum_method_portalsdk_update_firmware(void
    
);
uint16_t uniffi_portal_checksum_constructor_portalsdk_new(void
    
);
uint32_t ffi_portal_uniffi_contract_version(void
    
);

