/* eslint-disable no-unused-vars */
export enum RealmSchema {
  KeeperApp = 'KeeperApp',
  Wallet = 'Wallet',
  WalletDerivationDetails = 'WalletDerivationDetails',
  WalletPresentationData = 'WalletPresentationData',
  BIP85Config = 'BIP85Config',
  ActiveAddresses = 'ActiveAddresses',
  UTXO = 'UTXO',
  Transaction = 'Transaction',
  TransactionToAddressMapping = 'TransactionToAddressMapping',
  WalletSpecs = 'WalletSpecs',
  WalletShell = 'WalletShell',
  WalletShellInstances = 'WalletShellInstances',
  Vault = 'Vault',
  VaultSpecs = 'VaultSpecs',
  VaultShell = 'VaultShell',
  VaultSigner = 'VaultSigner',
  XpubDetails = 'XpubDetails',
  VaultPresentationData = 'VaultPresentationData',
  VaultShellInstances = 'VaultShellInstances',
  SignerPolicy = 'SignerPolicy',
  TriggerPolicy = 'TriggerPolicy',
  SigningServerSetup = 'SigningServerSetup',
  Backup = 'Backup',
  UAI = 'UAI',
  Notification = 'Notification',
  AdditionalNotes = 'AdditionalNotes',
  VersionHistory = 'VersionHistory',
  BackupHistory = 'BackupHistory',
  StoreSubscription = 'StoreSubscription',
}
