export enum RealmSchema {
  KeeperApp = 'KeeperApp',
  Wallet = 'Wallet',
  WalletDerivationDetails = 'WalletDerivationDetails',
  WalletPresentationData = 'WalletPresentationData',
  WalletSpecs = 'WalletSpecs',
  WalletShell = 'WalletShell',
  WalletShellInstances = 'WalletShellInstances',
  Vault = 'Vault',
  VaultShell = 'VaultShell',
  VaultSigner = 'VaultSigner',
  VaultShellInstances = 'VaultShellInstances',
  InheritancePolicy = 'InheritancePolicy',
  TriggerPolicy = 'TriggerPolicy',
  TwoFADetails = 'TwoFADetails',
  NodeConnect = 'NodeConnect',
  UserTier = 'UserTier',
  UAI = 'UAI',
}
