/* eslint-disable no-unused-vars */
export enum RealmSchema {
  KeeperApp = 'KeeperApp',
  Wallet = 'Wallet',
  WalletDerivationDetails = 'WalletDerivationDetails',
  WalletPresentationData = 'WalletPresentationData',
  BIP85Config = 'BIP85Config',
  UTXO = 'UTXO',
  UTXOInfo = 'UTXOInfo',
  Label = 'Label',
  Transaction = 'Transaction',
  TransferPolicy = 'TransferPolicy',
  TransactionToAddressMapping = 'TransactionToAddressMapping',
  WalletSpecs = 'WalletSpecs',
  Vault = 'Vault',
  VaultSpecs = 'VaultSpecs',
  VaultSigner = 'VaultSigner',
  XpubDetails = 'XpubDetails',
  VaultPresentationData = 'VaultPresentationData',
  SignerPolicy = 'SignerPolicy',
  TriggerPolicy = 'TriggerPolicy',
  Backup = 'Backup',
  NodeConnect = 'NodeConnect',
  UAI = 'UAI',
  AdditionalNotes = 'AdditionalNotes',
  VersionHistory = 'VersionHistory',
  BackupHistory = 'BackupHistory',
  StoreSubscription = 'StoreSubscription',
}
