export enum hcStatusType {
  HEALTH_CHECK_SUCCESSFULL = 'HEALTH_CHECK_SUCCESSFULL',
  HEALTH_CHECK_FAILED = 'HEALTH_CHECK_FAILED',
  HEALTH_CHECK_SKIPPED = 'HEALTH_CHECK_SKIPPED',
  HEALTH_CHECK_MANAUAL = 'HEALTH_CHECK_MANAUAL',
  HEALTH_CHECK_SIGNING = 'HEALTH_CHECK_SIGNING',
  HEALTH_CHECK_SD_ADDITION = 'HEALTH_CHECK_ADDITION',
  HEALTH_CHECK_REGISTRATION = 'HEALTH_CHECK_REGISTRATION',
  HEALTH_CHECK_VERIFICATION = 'HEALTH_CHECK_VERIFICATION',
}
