export const COLDCARD_SS_EXPORT = {
  data: {
    account: 13,
    bip44: {
      deriv: "m/44'/1'/13'",
      first: 'mniHcs7yEgqVJ6D3YUV6g6Y4HtTzMo7kHM',
      name: 'p2pkh',
      xfp: '3938DFB4',
      xpub: 'tpubDC9LihH2FxGQaUPyer4K7vn53tTawMZidZ5Uqfn2hLGpB8MVSyPVz2h1EAJycLv3PnBWVRg2bCTEM5fgfHnFthPokCSpzoYscwo9tqb4iwa',
    },
    bip48_1: {
      _pub: 'Upub5Sk2WcfjmoG5aSTr2L5qnuu9Kfnthn4h5wKiTrKMS8cTwZLq9pWtQ7mJFmNqULmbS5PE2WtrpafoKq9FMTv8i6tiRG8qgBiNC61MERtcn4f',
      deriv: "m/48'/1'/13'/1'",
      name: 'p2sh-p2wsh',
      xfp: 'CD4AFC61',
      xpub: 'tpubDEiMpcmjNAHbyZ4g2vxpo2BDSuHdJfrf4dq1FKncYHfbDxtKDcUPKdYckiNuS8ThDSCa1wCHrTAzYhrncBrTqmH9FQs1i3N4hVWpaDXQSoP',
    },
    bip48_2: {
      _pub: 'Vpub5maHpHLevUoZUoC6wGMgsZfgSPCwgc1a4P12TLtEYMJPguBPiFNFmJHtr8RTqLcUsQvNbwQRoZQQnJ3EDv3NpBo4yBXSHri9eiqxZXsAq7C',
      deriv: "m/48'/1'/13'/2'",
      name: 'p2wsh',
      xfp: '299B6A14',
      xpub: 'tpubDEiMpcmjNAHc2cbp7WT3farFPeZELsp37xz6TRTcGVydvCueXPAC4kR5KsTwoDefF8cuqt7JNmZ47t9CkwZh9cVtvzZBjoYMtQHnWjqtJae',
    },
    bip49: {
      _pub: 'upub5DgUm7PTrXRUWdLXaMg7uRKqwoVbSYjAP7QP4STEgjBYdoD5MGKgHf18UqXggdgcxYLe785NviymaqdvD3EzX2STG6aZRhaFAx4qoKrgyis',
      deriv: "m/49'/1'/13'",
      first: '2NEZQnS6osvnCJ2Vo295wWiAimB6t4bYLfY',
      name: 'p2sh-p2wpkh',
      xfp: '22386C3B',
      xpub: 'tpubDCYuCMDu1r1NLK6jXd25jbwinq2bFoCig5ZLmBC3Af55YPKUBTfTJHeNnVVECrbcyNDxy8NvqosTvsyDkzLGoAwYviR8rxgwa5rBj9AT4Ct',
    },
    bip84: {
      _pub: 'vpub5ZDk9mRXaiWmRfy3GRUPWXwtAVAuwUX8iSf4AYvMBywCGJzsVew4xopmy87ZJURcpvz7U8yK4PnwY6EdHhLFqhzh24ud3zzDbJJEop5v42g',
      deriv: "m/84'/1'/13'",
      first: 'tb1qclvfyg5v9gahygk5la56afevcnpdxt203609gp',
      name: 'p2wpkh',
      xfp: 'ED0DF249',
      xpub: 'tpubDDFuHLb3bMZBQ4Y8PL2j8dUFqYZTp71C6JHo5tmGHuSr7oJ35C7HMNotFa7WpnghS7kdafgJWpL5zqxN7x1XKcpBpM3muMHRii1wLvCKoYT',
    },
    chain: 'XTN',
    xfp: 'B47CF9C5',
    xpub: 'xpub661MyMwAqRbcFJ7KPwUrnNTRMcfDqgNuuq5zmJ9AJKe8v9iSVVttsh2vgJKCSJqoZSuGM5KVzQ6Nc7utgwq64UzhsX3B6Mm6CcvTEEDdipF',
  },
  rtdName: 'application/json',
};

export const SEEDSIGNER_SS_EXPORT = {
  data: "[e1e66310/84'/1'/0']vpub5Yaq4u2kgKTnHrv67VHj8FswPcZu3K42rUhXk59kcZuTnDQDkwks19kT5jmpdtseQN9y63tiFvGPcas8AH7wBPG6nxEbG7TP5Kp269gdV87",
};

export const KEYSTONE_SS_EXPORT = {
  data: 'UR:CRYPTO-ACCOUNT/OEADCYHSROZTSSAOLYTAADMWTAADDLOSAOWKAXHDCLAOCAJTGTMTWMWENSNYRHGUCFFTVAZTWKMSAMFWLTCKOECKKPBSFYJPDIVAGDBWRTAAAAHDCXLTDTFYHFLPINBNIABDENLNVLWKRTCYYTDRIMBEMYOEOYZSETDPKENEDAWTTKNEDPAHTAADEHOEADADAOADAMTAADDYOTADLNCSGHYKADYKAEYKAOCYHSROZTSSAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYBTLYAEWDFTKBHTFX',
};

export const PASSPORT_SS_EXPORT = [
  {
    data: 'UR:BYTES/82-14/LPCSGMBACFATDYCYGYTIIAJKHDLRBSFDAEFMJPKEBWGUDLAODIGRCHATFWCADWCPJTFMFGFDDLBBCWKBGLCLGTFZHPCNKSFWDTAAEOGMJKGYCYCNGTKOFDCFINCWGHDLFHAMJNGDGEJLGSDSCNAAAMENDPGACXIOIDIYGSGEBECKFHJLEHINBEAAHPCHIECEFXCSCFCEASFWDPADKSCKJSJZIOAOFZHEJLGOFSBSFEFTIADKGTJKJLGOJEENFNKSETFLGABKIAHKKOCSINGUCMIAJOJEDTCTHPIHBGLKYNLD',
  },
  {
    data: 'UR:BYTES/83-14/LPCSGUBACFATDYCYGYTIIAJKHDLRKIDWCXCPIDINJOEEEECPFTCXKGCPKSJOKPIDCPFTCXCPJYJOKPIDFYFXIDKSGEKSKNGUHFGOKPETKPHDFYJLEEKPECHKGRFGGMJEETFGIAINECFEFWKPGDGEJNHKGOKSGMEMIAJOJKINEHEEIOGEISGMFEGOFPHDGTIEIEJLJNJTIHGHHTJOJYHGGOGREEFDKTECISGOHKHDGRGEGRGYGRKPKNGEHDHGGOIEIAHDFYGREEEOHDGLIOKNGEKOEHHDINGOIAHSJTMDINSE',
  },
  {
    data: 'UR:BYTES/84-14/LPCSGHBACFATDYCYGYTIIAJKHDLRBWEHEMDKHNJNGABEKGCYDKHEFYDRGECEJYJTATADDNFWESBGFMGRKEKPBNJKDSFTJYHFFRFMFRAYDKJTBTKEKEISHDFEFMEHKSHYGEISKSAYCYCSISJPBWBWFMEHIYAMFNBDCSFLGAJYETESAXIMDRJOBWESETIYFXCMBSIHDRIEGDBBEHDRHHHFCAATDRKTCXIDDYDRKNIOCXFWGYGLKNGAGHFXKTGOJLFPDYGAFXGEGAGAEYBGDTAEEHHSBTASGDDKJKINTELPRDGM',
  },
  {
    data: 'UR:BYTES/87-14/LPCSHGBACFATDYCYGYTIIAJKHDLRHTGSFXIYEEEOKPGRJEFGIOGUGEEEKTGEJYGUEYHDFLIHENEOJTINEMINJOFPJLFXGTGSFPHSGUJTFDHTIYFEEMKPKSGRJYGTFPENFEESHKHTFWHDIMGEGSHSIDHFFLFYEEKKIHIDKKHSGSKKFWHTGREYIYESGHGUECHSISEEGHCPKIDWCXCPIDINJOEEETHEEYCPFTCXKGCPKSJOKPIDCPFTCXCPJYJOKPIDFYFGFEEMFDGLHTEEGLFPFXHFEMIMEMFDGSKNOXWTBEUR',
  },
  {
    data: 'UR:BYTES/88-14/LPCSHDBACFATDYCYGYTIIAJKHDLRKIDWCXCPIDINJOEEEECPFTCXKGCPKSJOKPIDCPFTCXCPJYJOKPIDFYFXIDKSGEKSKNGUHFGOKPETKPHDFYJLEEKPECHKGRFGGMJEETFGIAINECFEFWKPGDGEJNHKGOKSGMEMIAJOJKINEHEEIOGEISGMFEGOFPHDGTIEIEJLJNJTIHGHHTJOJYHGGOGREEFDKTECISGOHKHDGRGEGRGYGRKPKNGEHDHGGOIEIAHDFYGREEEOHDGLIOKNGEKOEHHDINGOIAHSWMLPCYDL',
  },
  {
    data: 'UR:BYTES/90-14/LPCSHTBACFATDYCYGYTIIAJKHDLRENGEENJOIDAXIEFMDKJYDACKCSBTGMAMCHBYBZHNISBECTBTDMDTCSIYHLAHFMHNFHCNIYDWBTJKHEBKFTHFJKDLDWFYIDGHBZJPGYBZCWHLJPGYBKATIMAYBDCPCTASEEJYHKFYJNCTCEIOCNCYJEDLGUBSGWIAINGRDTGRAYEYAACSFGGRLBGWKSKTJPAMCNIAJOFLGYCHFYAAAEFWJPIAGLCYBYFNDMGDDWKTKIFLETDAIAJPHNAXGWKPCLHLFMADEEHSOLNNCLSG',
  },
  {
    data: 'UR:BYTES/91-14/LPCSHPBACFATDYCYGYTIIAJKHDLRGMFGLBJZIHKTFPHLFRAOFDCWCFFLBSESCTDPECGEEYHYENBDDLIEJNDKIMGMIDENIMHSGRATAEDMGLHPBKDNBAGREHESKPJZFYBKGRCMKOGEDIGWHNBYDSBSDTDNBTJECSCAEEFXKTJSKSKKDPGSJTHHADCLINCTCYFPJOFWDPCSHYGSFEFTJLDNBGCKDSBSKNCTGDHKDTCWFTAXFLCNJZHFKTHYHSBKEHJLIMHLKKKSETCLHGJYJKGHHHBZFPEOFZGEETAAFLVWSNMS',
  },
  {
    data: 'UR:BYTES/93-14/LPCSHLBACFATDYCYGYTIIAJKHDLRIMJEEMAOIHHHKOCFCPJLKSJYFEFHDAHKEHEYFGCYEEGMEMETKKCXHGIAKOJYHNKSINKEAEHFCKHGKTJPFGDNKECWJOISCXGRFMIMCXCFGLCFIYGWGYCAKTDKJPHTGHGSCWHTEYJNHPISGAHLBDCLCXGYAMGMCKHDDYEYDIAEBSJNADHGGLECISJSEMEMEEIYBTFLFTHLHFCAFRGTBYECKPCTHSIMDIDYFXCLGDGRFPFXKSFHCNFTHLAEBKBTADHEFGHKGRDLKBKGREEC',
  },
  {
    data: 'UR:BYTES/94-14/LPCSHYBACFATDYCYGYTIIAJKHDLRCHKSKGAOKPCWBWKTHPKIHSJPADGRKKHPFDENCYHEBKAEDSFHHLBKDKCTHGBDDSDYGUJNCKJEGUFHFGEEFZGRIDGWDLDMHEFWEOFWCMDSBNASAYAMKTCHBBISHHIDFTKEHPEOEMHSCTKGHDHPHTCHDRIOEOIHHDBYFNKSKOCTGEHLBYBYJLFZEHFNFTECKKFWHSJOAOKECPKTEYJNDSGDENFYKTDKKEBYFXCHFPEMFMDMFNFRGYKKDNGLEHCKDRGLENAOFSCWYNPKVDAA',
  },
  {
    data: 'UR:BYTES/95-14/LPCSHEBACFATDYCYGYTIIAJKHDLRGHINGHDLHFIEISFPKTFSDKJSHGEMCAIABGFSEEGDASGWJTFDFNFXESDECXFGGWECGTFEHPDLCACLAEDEKNISFPDKHLJZEEINJYCAFWIYFPGAJSHEGWCAGSIOGLGMFEAYJNFLBBJLDAGOJKDRECFEFPKSCSIYIHJKFXGDCMGOKNAABDJYKNDADEENIDKPDAESFHBDBTDSBKCPHPFGFXHTCFBSAOESIOHLDNDAHNJEDIDAENJEDPCXJYHHGSHLKBKSIMHLFDIEWSJZETGD',
  },
  {
    data: 'UR:BYTES/97-14/LPCSHSBACFATDYCYGYTIIAJKHDLRGWCFJPJNDYAYKIFPAMBAKTKIDRKKKTENGUHKGLHYKBJZENEHKKBBDPIACHCLDKBTATBZIOJKFTGRAXBNDYCHBAKIBWDSCHAYGHIEISASGECXCPFDGSDREHBGIYFSCXCFFGFGKGKTFHCNBKBEJZFPBBGUGYKSCYHGDECNJTHFADHPECGLFNDMDICXBSGHBGBGHDFWCHCSCPHKCLJYHNKOBNGTIAHYJYISJKAOGUEYBZCYBAEEAAHKCMHSFPBYEMIADSCEGADWIDSFSSQD',
  },
  {
    data: 'UR:BYTES/98-14/LPCSIDBACFATDYCYGYTIIAJKHDLRJOKPIDFYFYFYGTFPEHIEIDHSEHEYESGHFEJKKPEEGRGEFWJOGYECISJKINGUIDJNKSFEGREEFDKOJLJPIHIMGTETGUJTFDKTHKECJKISFGKNGDFWJNGSGUGHEYGUIMJLJKKOGEIMENINJSKNJKJKECIOHSECISIHFDGHEOFPJSFLJEJEEMJYGOGUJYEMIMFXGRGOJNGUGUGLJSKNHSENHFHFIOHTCPDWCXCPIYINJPJKJYCPFTCXCPJYIDEHJSJEEYJEENECIMLGAARN',
  },
  {
    data: 'UR:BYTES/100-14/LPCSIEBACFATDYCYGYTIIAJKHDLRJKAEJKGDHGAAGRFDGUHFKTGEGOFZHDDWBGCSFMCHIOIEBDCAEMCKGHBYAOHHENCLHEFGKODWDTBEEYDYCFGHFHAHATEHHNFYHNIDJZJYCECMDRBNCSHNJLHSHNDTHTJTHYIMCYIEJLKIINJYHGFECHFEDWCMAXJPASCFKPKOJLDEJKCFAHBTGMFZCYCFHGDNDWCSEYKGKTJZCMAXHLDSADETFZFNKBGRKNBYHDEYGSBTGTJSHKHKHEAHJOKPIDCPFTCXCPJYCKATWTDY',
  },
  {
    data: 'UR:BYTES/101-14/LPCSIHBACFATDYCYGYTIIAJKHDLRIOBADKBBIHFRDSGOKBEHCNDPKSCXIHHKKPLBFMCXGLEHFRDPBEHKBDCNGDGAIMIOHYINKOBGHDHKCWKGKIKGFWHHBYAXFYJEAEDLFSCXFHFDBDBGKIHHGHBBGDKKFTCKCFJKCNKNKNHYGYAEIABSDRFPCAIOBNJSIMESDECWGAJZFLDIHSFZFHKPDSKBINISJOHLCHCHFEFYFNLBBSJZFZCECXAXFHAXJSGUDPESDEGSGEBYCXEHJKDTDYKOBWEHHTCHGWEHMOIEKSBB',
  },
  {
    data: 'UR:BYTES/102-14/LPCSIYBACFATDYCYGYTIIAJKHDLRDWCXCPKSIYJOCPFTCXCPFYENESFPEYFXEHFWCPDWCXCPJTHSJNIHCPFTCXCPJOEYKTJKISCPDWCXCPHEJOKPIDCPFTCXCPHFJOKPIDECJTENEOFDEOEMKKKOGOINGUHTKPISHSFPIMKOJSJSHDGSFGFDKKECFYFPHGFGIOIMKOFLHFKSHFENEHKPJSEYHFFXJSIHEMGDKKGUGHHTGSHFKSIAFGKOIYGSJEIMFEKNETJEFEKOFGGLKSJEKPFWKKJEETHTHTJSHYGUHGQZ',
  },
  {
    data: 'UR:BYTES/104-14/LPCSISBACFATDYCYGYTIIAJKHDLRGABKGYLBDSIMHSAMHFFZBZFPHDCSCTJPDPFGBEDPHPGHGYHPCTJNDAJEDNECCHFGFXGYKGFLBWFWDTIYJNJEDMJTBZCKAECXCABGDMFLDRBWEODSGYGLBGKGAEJSDIAHCWENESGUFSJYGWCLDNBGCPDPKSLBJPAAEHDKJZBKGSHFFMKSDYKSGTGMIMKNKGCPIMKKBSJOGTKPGHGMCKAYEHKTGDDKCTKGIHADEYEHHTKOHKKTIHJLGLHTHHDKBGEMHKKEBSDYFRYKPAIE',
  },
  {
    data: 'UR:BYTES/105-14/LPCSINBACFATDYCYGYTIIAJKHDLRAOFYINGAEHJNJKLBEYBTBWCMHSJPEMHDDSDEAMESFPEEIHKNKGGDEMECCAFWJSBACFBWAHJPIDHYBAHPFYGYIDGAEMJPIACEGSGTBSCHFWBDFZDNJEHSBNHNGEKPJYAYCLJOCYDRGSCHBBHDAXJEDNDIKNBDENFXETCSGOJEGRDEHGKPCFDEKGBWCFAYAEKSEMKEHDEHBNJSAHGTKOHYDMKOGWKPJOGLGTBWCNJNJEBYHKCAEEFEIOIOCXFPIDDYFNBKKBHYAHFZOXSB',
  },
  {
    data: 'UR:BYTES/106-14/LPCSIMBACFATDYCYGYTIIAJKHDLRECGOESKOIHIMJPHFHFHFJPFPEEGMHDHGJSGHJLISESKSGEFEIHFXIMJEKPEYHDIYJNFGFEJPKTFPEOGSGSKNGOEMIYINFGCPDWCXCPIYINJPJKJYCPFTCXJTKPJZJZDWCXCPIEIHJPINKOCPFTCXCPJNDLEEETDIDLEHDIDLDYDIDLEHDICPDWCXCPKSIYJOCPFTCXCPENECEYEHEHFWEOFGCPDWCXCPJTHSJNIHCPFTCXCPJOEYJKISDPJOEYKTJKISCPDWLDQZNSLN',
  },
  {
    data: 'UR:BYTES/107-14/LPCSJEBACFATDYCYGYTIIAJKHDLRBDCEKTEMADCHAAAYHKINKOHEGSGTETHGBNDLIOFHDPFHJPIYCYEHENGUAOATEMHHGDGHBWBSFRBZIHHLHPGHIDATBBBEGLJSFRGSDMEHFTGUFDKEHLDKCTDABBFLEEGDJNGYIECFGYFGESHFEHFNCFJSBNFHESAOHPCMKKIMJNGWISHHADBDEYIHIHENJYCNCTHNHGEEIMDLGEESCNBAKBEHCNDIBYGOKPBAJOGLASIYJLBSISAXDWCEFDGLLBCWEEBDDIETFZRPRFFR',
  },
  {
    data: 'UR:BYTES/108-14/LPCSJZBACFATDYCYGYTIIAJKHDLRGUFNDRHLBECTHHDPEHGDCMFSKOGDADCNDYCYAOGTKOCKKGGWAYBAGHAEFSCSATAXGTHTKBINGSEEFNASCFDTBBDYBTINCPEYJZBDECECEYHHEHEYCTFWBGGMJZATAEHTDLCTHDCFFHHNADDWFHINFSJZBDENGLFEIEGYBNBAGDHYHHAHKEGMGTDTKTEECSBWDAETCHDPADJNFZEEGTGLEEDTKIBZFNESGODKHTHNHSDPHKCMCMIACTIMGTKBAOADCTJZGHFYRHFZBGES',
  },
  {
    data: 'UR:BYTES/109-14/LPCSJNBACFATDYCYGYTIIAJKHDLRKPIHFHKPFLGSFYHLDSBDDABDASHLDNFXBDECAAATKPHNGWJKBTBDGEJYHYGABWIMKPKTGLINIEBZGAGLKBAXFLBNDIBZHGJZDYBSCPCTIAJLDLKEKODLJSCMCHFYKSJSHGFYHGKPJSJLGTFXJZCWFYDLJNIEHGHFDIEYBNCHHGHHGHCNGOCTCEBKCPFMCSDYJYKPCYFHCMKPGOCMDRIMFRHPBBGUFYAOKTDNCXBTFMHPDKEMDSHDJNAEHYGAESDEEMFNBAEHLFCSGTEY',
  },
];
