require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

# ignoring .xocde.env as we use our own configs for dev and production
# production = ENV["PRODUCTION"] == "1"

def common_pods
  config = use_native_modules!

  # Flags change depending on the env values.
  # flags = get_default_flags()
  # ignoring flags as we use our own configs for dev and production

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => false,
    :hermes_enabled => false,
    :fabric_enabled => true,
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

target 'hexa_keeper' do
  common_pods()
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end

target 'hexa_keeper_dev' do
  common_pods()
end


post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end