appId: ${APPID}
---
# - runFlow: login.yaml
- tapOn:
    id: btn_AppSettingsIcon
- assertVisible:
    id: 'btn_back'
- assertVisible: 'App Settings'
- assertVisible: 'Configure your app here'
- assertVisible:
    id: 'btn_App_Backup}'
- assertVisible:
    id: 'view_Biometrics'
- assertVisible:
    id: 'view_Dark_Mode'
- assertVisible:
    id: 'view_Node_Settings'
- assertVisible:
    id: 'view_Version_History'
- assertVisible:
    id: 'view_Tor_Settings'
- assertVisible:
    id: 'view_Language_&_Currency'
- assertVisible:
    id: 'view_ KeeperTelegram'
- assertVisible:
    id: 'view_keeperTwitter'
- assertVisible:
    id: 'btn_FAQ'
- assertVisible:
    id: 'text_termsCondition'
- assertVisible:
    id: 'text_privacyPolicy'
- tapOn:
    id: 'view_Dark_Mode'
    delay: 1000
- tapOn:
    id: 'view_Dark_Mode'
    delay: 1000
- runFlow: exportseed.yaml
- runFlow: versionhistory.yaml
- tapOn:
    id: 'btn_back'
