export const CREATE_CHANNEL = 'CREATE_CHANNEL';
export const JOIN_CHANNEL = 'JOIN_CHANNEL';
export const BITBOX_SETUP = 'BITBOX_SETUP';
export const BITBOX_REGISTER = 'BITBOX_REGISTER';
export const TREZOR_SETUP = 'TREZOR_SETUP';
export const TREZOR_REGISTER = 'TREZOR_REGISTER';
