export const CREATE_CHANNEL = 'CREATE_CHANNEL';
export const JOIN_CHANNEL = 'JOIN_CHANNEL';
export const SIGNED_TX = 'SIGNED_TX';
export const SET_NETWORK = 'SET_NETWORK';
export const CHANNEL_MESSAGE = 'CHANNEL_MESSAGE';

// EMIT MODES
export const EMIT_MODES = {
  ADD_DEVICE: 'ADD_DEVICE',
  REGISTER_MULTISIG: 'REGISTER_MULTISIG',
  SIGN_TX: 'SIGN_TX',
  HEALTH_CHECK: 'HEALTH_CHECK',
  VERIFY_ADDRESS: 'VERIFY_ADDRESS',
  PURCHASE_SUBS: 'PURCHASE_SUBS',
};

// whirlpool events
export const WHIRLPOOL_LISTEN = 'WHIRLPOOL_LISTEN';
export const WHIRLPOOL_WORKING = 'WHIRLPOOL_WORKING';
export const WHIRLPOOL_SUCCESS = 'WHIRLPOOL_SUCCESS';
export const WHIRLPOOL_FAILURE = 'WHIRLPOOL_FAILURE';
export const WHIRLPOOL_ERROR = 'WHIRLPOOL_ERROR';

//Inheritance Tools
export const BUY_NEW_HARDWARE_SIGNER = 'BUY_NEW_HARDWARE_SIGNER';
export const CANARY_WALLETS = 'CANARY_WALLETS';
export const ASSISTED_KEYS = 'ASSISTED_KEYS';
export const SECURE_USAGE_TIPS = 'SECURE_USAGE_TIPS';
export const SAFE_KEEPING_TIPS = 'SAFE_KEEPING_TIPS';
export const MASTER_RECOVERY_KEY = 'MASTER_RECOVERY_KEY';
export const PERSONAL_CLOUD_BACKUP = 'PERSONAL_CLOUD_BACKUP';
export const WALLET_CONFIG_FILES = 'WALLET_CONFIG_FILES';
export const BACKUP_AND_RECOVERY_FILES = 'BACKUP_AND_RECOVERY_FILES';
export const LETTER_OF_ATTORNEY = 'LETTER_OF_ATTORNEY';
export const RECOVERY_INSTRUCTIONS = 'RECOVERY_INSTRUCTIONS';
export const PRINTABLE_TEMPLATES = 'PRINTABLE_TEMPLATES';
export const INHERITANCE_TIPS = 'INHERITANCE_TIPS';
export const RECOVERY_PHRASE_TEMPLATE = 'RECOVERY_PHRASE_TEMPLATE';
export const TRUSTED_CONTACTS_TEMPLATE = 'TRUSTED_CONTACTS_TEMPLATE';
export const ADDITIONAL_SIGNER_DETAILS = 'ADDITIONAL_SIGNER_DETAILS';
