import Colors from 'src/theme/Colors';
import { extendTheme } from 'native-base';
import Fonts from 'src/constants/Fonts';

export const customTheme = extendTheme({
  fontConfig: {
    Inter: {
      100: {
        normal: Fonts.InterLight,
        italic: Fonts.InterLightItalic,
      },
      200: {
        normal: Fonts.InterRegular,
        italic: Fonts.InterItalic,
      },
      300: {
        normal: Fonts.InterMedium,
        italic: Fonts.InterMediumItalic,
      },
      400: {
        normal: Fonts.InterSemiBold,
        italic: Fonts.InterSemiBoldItalic,
      },
      500: {
        normal: Fonts.InterBold,
        italic: Fonts.InterBoldItalic,
      },
      600: {
        normal: Fonts.InterRegular,
        italic: Fonts.InterItalic,
      },
      700: {
        normal: Fonts.InterRegular,
        italic: Fonts.InterItalic,
      },
      800: {
        normal: Fonts.InterRegular,
        italic: Fonts.InterItalic,
      },
      900: {
        normal: Fonts.InterRegular,
        italic: Fonts.InterItalic,
      },
    },
  },
  fonts: {
    heading: 'Inter',
    body: 'Inter',
    mono: 'Inter',
  },
  colors: {
    light: {
      buttonText: Colors.headerWhite,
      modalGreenSecButtonText: Colors.headerWhite,
      modalWhiteButton: Colors.headerWhite,
      white: Colors.headerWhite,
      headerWhite: Colors.headerWhite,

      primaryGreen: Colors.TagLight2,
      greenText2: Colors.TagLight2,

      primaryBackground: Colors.secondaryCreamWhite,
      receiveQrBackground: Colors.secondaryCreamWhite,
      QrCode: Colors.secondaryCreamWhite,
      fadedGray: Colors.secondaryCreamWhite,
      secondaryCreamWhite: Colors.secondaryCreamWhite,
      linkPreviewBackground: Colors.secondaryCreamWhite,
      seedCard: Colors.secondaryCreamWhite,
      greyBackground: Colors.secondaryCreamWhite,

      modalWhiteBackground: Colors.primaryCream,
      thirdBackground: Colors.primaryCream,
      whiteCircle: Colors.primaryCream,

      pantoneGreen: Colors.primaryGreen,
      SeaweedGreen: Colors.primaryGreen,
      dashedButtonBorder: Colors.primaryGreen,
      dashedButtonBorderColor: Colors.primaryGreen,
      primaryGreenBackground: Colors.primaryGreen,
      darkBorderGreen: Colors.primaryGreen,
      textGreen: Colors.primaryGreen,
      greenWhiteText: Colors.primaryGreen,

      pillText: Colors.TertiaryBlack,
      btcPillText: Colors.TertiaryBlack,

      pantoneGreenLight: Colors.pantoneGreenLight,

      modalWhiteContent: Colors.ashGreen,
      secondaryText: Colors.ashGreen,
      secondarySubtitle: Colors.ashGreen,
      coalGreen: Colors.ashGreen,

      modalGreenTitle: Colors.PrimaryBlack,
      backgroundbitSaga: Colors.PrimaryBlack,
      black: Colors.PrimaryBlack,

      modalGreenLearnMore: Colors.CastelGreenDark,

      dashedButtonBackground: Colors.TagDark2,
      dateText: Colors.TagDark2,

      boxSecondaryBackground: Colors.brightCream,
      textInputBackground: Colors.brightCream,
      seashellWhite: Colors.brightCream,
      seashellWhiteText: Colors.brightCream,
      ChampagneBliss: Colors.brightCream,
      appStatusTextColor: Colors.brightCream,
      whiteSecButtonText: Colors.brightCream,

      choosePlanIconBackSelected: Colors.DullGreenDark,
      choosePlanIconBack: Colors.PaleKhaki,
      hexagonIconBackColor: Colors.DullGreenDark,
      coffeeBackground: Colors.Coffee,
      yellowButtonBackground: Colors.MacaroniAndCheese,
      yellowButtonTextColor: Colors.Coffee,
      btcLabelBack: Colors.Periwinkle,
      primaryText: Colors.SecondaryBlack,
      learnMoreBorder: Colors.Coffee,
      textBlack: Colors.DarkGreen,
      greenText: Colors.TagDark3,
      sliderStep: Colors.TropicalRainForestDark,
      accent: Colors.MacaroniAndCheese,
      lightAccent: Colors.MacaroniAndCheese,
      hardWareImageBackGround: Colors.SoftJadeTint,
      GreyText: Colors.GreenishGrey,
      DarkGreyText: Colors.FeldgrauDark,
      Border: Colors.TagLight1,
      textColor: Colors.dullGreen,
      textColor2: Colors.DeepSpaceSparkle,
      copyBackground: Colors.dullGreen,
      sendCardHeading: Colors.DullGreenDark,
      divider: Colors.darkGrey,
      errorRed: Colors.redAlert,
      SlateGreen: Colors.SlateGreen,
      textWallet: Colors.TagDark5,
      indicator: Colors.OutrageousOrange,
      sendMax: Colors.JackoBean,
      inActiveMsg: Colors.SecondaryBlack,
      walletTypePillBack: Colors.Bisque,
      pillPlaceholderBack: Colors.LightKhaki,
      gradientEnd: Colors.TagDark3, // linearGradient
      error: Colors.CongoPink,
      LightGreenish: Colors.TagDark9,
      fadedblue: Colors.FadeBlue,
      forestGreen: Colors.TagLight1,

      lightSeashell: Colors.lightSeashell,
      BrownNeedHelp: Colors.primaryBrown,
      policySubtitle: Colors.GreenishGrey,
      balanceText: Colors.GreenishGrey,
      GreenishGrey: Colors.GreenishGrey,
      RecoveryBorderColor: Colors.RussetBrownLight,
      primaryBrown: Colors.primaryBrown,
      whiteText: Colors.dullGreen,
      LightBrown: Colors.LightBrown,
      SignleSigCardPillBackColor: Colors.PaleTurquoise,
      dropdownSeparator: Colors.Taupe,
      lightSkin: Colors.LightSkin,
      feeInfoColor: Colors.SecondaryBlack,
      greyBorder: Colors.secondaryLightGrey,
      placeHolderTextColor: Colors.secondaryDarkGrey,
      dullGreyBorder: Colors.SilverMistTranslucent,
      greyBorderTransparent: Colors.SilverMistTransparent,
      greyBorderTranslucent: Colors.secondaryLightGrey,
      border: Colors.separator,
      limeText: Colors.LimeYellow,
      greenTextDisabled: Colors.SlateGreen,
      overlayGreen: Colors.dullGreen,
      alertRedLight: Colors.redAlert,
      disabledDiamond: Colors.secondaryLightGrey,
      secondaryGrey: Colors.secondaryLightGrey,
      appStatusButtonBackground: Colors.WarmBeigeTranslucent,
      textDarkGreen: Colors.DarkGreen,
      labelColor2: Colors.LabelLight2,
      boxBackground: Colors.BoxGolden,
      borderBrown: Colors.primaryBrown,
      separator: Colors.separator,
      FlameOrange: Colors.FlameOrange,
      alertRed: Colors.redAlert,
      newBadgeGreen: Colors.NewBadgeGreen,
      textGreenGrey: Colors.GreenishGrey,
      errorToastBackground: Colors.ErrorToast,
      transactionDeatilInfo: Colors.GreenishGrey,
      transactionDeatilAddress: Colors.GreenishGrey,
      greenishGreyText: Colors.GreenishGrey,
      receiptBorder: Colors.secondaryLightGrey,
      brownBackground: Colors.primaryBrown,
      keyPadText: Colors.GreenishGrey,

      solidGreyBorder: Colors.greyBorder,
      menuCardTitleColor: Colors.secondaryDarkGrey,
      newDashedButtonBackground: Colors.SoftTealOverlay,

      LightGraycolor: Colors.LightGraycolor,
      DarkGreyText: Colors.GreenishGrey,
      darkBrownCircle: Colors.primaryBrown,
      lightBrownCircle: Colors.RussetBrownLight,
      sliderUnfilled: Colors.dullGreen,
      ctaFooterBackground: Colors.GreenishGrey,
      dullGreen: Colors.dullGreen,
      termsText: Colors.termsGrey,
      graphiteTranslucentBG: Colors.GraphiteTranslucent,
      SeaweedGreenTranslucentBG: Colors.SeaweedGreenTranslucent,
      modalSubtitleBlack: Colors.secondaryBlack,
    },
    dark: {
      modalWhiteContent: Colors.headerWhite,
      receiveQrBackground: Colors.headerWhite,
      yellowButtonTextColor: Colors.headerWhite,
      greenWhiteText: Colors.headerWhite,
      black: Colors.headerWhite,
      feeInfoColor: Colors.headerWhite,
      btcPillText: Colors.headerWhite,
      balanceText: Colors.headerWhite,
      textDarkGreen: Colors.headerWhite,
      headerWhite: Colors.headerWhite,

      primaryGreen: Colors.TagLight2,
      gradientEnd: Colors.TagLight2,

      QrCode: Colors.secondaryCreamWhite,
      secondaryCreamWhite: Colors.secondaryCreamWhite,

      dashedButtonBorderColor: Colors.primaryCream,

      SeaweedGreen: Colors.primaryGreen,

      pillText: Colors.TertiaryBlack,
      seashellWhite: Colors.TertiaryBlack,
      overlayGreen: Colors.TertiaryBlack,
      seedCard: Colors.TertiaryBlack,

      pantoneGreenLight: Colors.pantoneGreenLight,
      ChampagneBliss: Colors.pantoneGreenLight,

      coalGreen: Colors.ashGreen,

      primaryBackground: Colors.PrimaryBlack,
      modalGreenLearnMore: Colors.PrimaryBlack,
      yellowButtonBackground: Colors.PrimaryBlack,

      termsText: Colors.brightCream,
      appStatusTextColor: Colors.brightCream,

      buttonText: Colors.bodyText,
      modalGreenSecButtonText: Colors.TropicalRainForestDark,
      disabledDiamond: Colors.secondaryLightGrey,
      modalSubtitleBlack: Colors.bodyText,
      primaryGreenBackground: Colors.SecondaryBlack,
      modalWhiteBackground: Colors.ModalBlack,
      modalWhiteButton: Colors.DullGreenDark,
      modalGreenTitle: Colors.bodyText,
      dashedButtonBackground: Colors.DullGreenDark,

      choosePlanIconBackSelected: Colors.DullGreenDark,
      choosePlanIconBack: Colors.darkGrey,
      hexagonIconBackColor: Colors.DullGreenDark,

      coffeeBackground: Colors.primaryBrown,
      btcLabelBack: Colors.PeriwinkleDark,
      white: Colors.SecondaryBlack,
      FlameOrange: Colors.FlameOrange,
      primaryText: Colors.bodyText,
      secondaryText: Colors.bodyText,
      learnMoreBorder: Colors.bodyText,
      textBlack: Colors.bodyText,
      greenText2: Colors.TropicalRainForestDark,
      sliderStep: Colors.TropicalRainForestDark,
      accent: Colors.ToastBg,
      lightAccent: Colors.ToastBg,
      textInputBackground: Colors.SecondaryBackgroundDark,
      GreyText: Colors.bodyText,
      dateText: Colors.bodyText,
      Border: Colors.bodyText,
      textColor: Colors.dullGreen,
      textColor2: Colors.secondaryLightGrey,
      copyBackground: Colors.dullGreen,
      sendCardHeading: Colors.DullGreenDark,
      SlateGreen: Colors.SlateGreen,
      divider: Colors.darkGrey,
      errorRed: Colors.redAlert,
      textWallet: Colors.TagDark5,
      indicator: Colors.OutrageousOrange,
      sendMax: Colors.JackoBean,
      inActiveMsg: Colors.secondaryLightGrey,
      walletTypePillBack: Colors.LabelDark1,
      pillPlaceholderBack: Colors.LabelDark1,
      error: Colors.CongoPink,
      backgroundbitSaga: Colors.secondaryLightGrey,
      darkBorderGreen: Colors.TagDark9,
      fadedGray: Colors.bodyText,
      fadedblue: Colors.FadeBlue,
      forestGreen: Colors.TagLight1,
      pantoneGreen: Colors.DullGreenDark,
      seashellWhiteText: Colors.bodyText,
      lightSeashell: Colors.lightSeashell,
      BrownNeedHelp: Colors.primaryBrown,
      policySubtitle: Colors.bodyText,
      GreenishGrey: Colors.GreenishGrey,
      RecoveryBorderColor: Colors.RussetBrownLight,
      primaryBrown: Colors.primaryBrown,
      LightGraycolor: Colors.LightGraycolor,
      whiteText: Colors.dullGreen,
      LightBrown: Colors.LightBrown,
      SignleSigCardPillBackColor: Colors.Turquoise,
      dropdownSeparator: Colors.Taupe,
      lightSkin: Colors.secondaryDarkGrey,
      hardWareImageBackGround: Colors.hardWareDarkImageBackGround,
      greyBorder: Colors.secondaryLightGrey,
      greyBorderTransparent: Colors.SilverMistTransparent,
      greyBorderTranslucent: Colors.secondaryLightGrey,
      border: Colors.SilverMistTransparent,
      placeHolderTextColor: Colors.secondaryDarkGrey,
      dullGreyBorder: Colors.separator,
      placeHolderTextColor: Colors.darkGrey,
      linkPreviewBackground: Colors.ModalBlack,
      limeText: Colors.LimeYellow,
      greenText: Colors.bodyText,
      greenTextDisabled: Colors.SlateGreen,
      alertRedLight: Colors.redAlert,
      secondaryGrey: Colors.separator,
      appStatusButtonBackground: Colors.WarmBeigeTranslucent,

      labelColor2: Colors.LabelDark2,
      boxBackground: Colors.SecondaryBackgroundDark,
      boxSecondaryBackground: Colors.SecondaryBlack,
      borderBrown: Colors.SilverMistTransparent,
      separator: Colors.separator,
      alertRed: Colors.AlertRedDark,
      newBadgeGreen: Colors.GreenishGrey,
      textGreen: Colors.bodyText,
      textGreenGrey: Colors.bodyText,
      thirdBackground: Colors.SecondaryBlack,
      errorToastBackground: Colors.ErrorToastDark,
      transactionDeatilInfo: Colors.darkGrey,
      transactionDeatilAddress: Colors.bodyText,
      greenishGreyText: Colors.darkGrey,
      receiptBorder: Colors.separator,
      modalUnitColor: Colors.SoftGray,
      brownBackground: Colors.DullBrown,
      keyPadText: Colors.SoftGray,
      solidGreyBorder: Colors.separator,
      menuCardTitleColor: Colors.darkGrey,
      secondarySubtitle: Colors.darkGrey,
      dashedButtonBorder: Colors.separator,
      newDashedButtonBackground: Colors.FadedMossOverlay,
      whiteSecButtonText: Colors.SoftGray,
      DarkGreyText: Colors.RichBlackDark,
      greyBackground: Colors.darkGrey,
      whiteCircle: Colors.bodyText,
      darkBrownCircle: Colors.primaryBrown,
      lightBrownCircle: Colors.RussetBrownLight,
      sliderUnfilled: Colors.CharcoalGreen,
      ctaFooterBackground: Colors.SecondaryBlack,
      dullGreen: Colors.DeepCharcoalGreen,
      graphiteTranslucentBG: Colors.GraphiteTranslucent,
      SeaweedGreenTranslucentBG: Colors.SeaweedGreenTranslucent,
    },
  },
  config: {
    initialColorMode: 'light',
  },
});

export default customTheme;
