import Colors from 'src/theme/Colors';
import { extendTheme } from 'native-base';
import Fonts from 'src/constants/Fonts';

export const customTheme = extendTheme({
  fontConfig: {
    FiraSans: {
      100: {
        normal: Fonts.FiraSansLight,
        italic: Fonts.FiraSansLightItalic,
      },
      200: {
        normal: Fonts.FiraSansRegular,
        italic: Fonts.FiraSansItalic,
      },
      300: {
        normal: Fonts.FiraSansMedium,
        italic: Fonts.FiraSansMediumItalic,
      },
      400: {
        normal: Fonts.FiraSansSemiBold,
        italic: Fonts.FiraSansSemiBoldItalic,
      },
      500: {
        normal: Fonts.FiraSansBold,
        italic: Fonts.FiraSansBoldItalic,
      },
      600: {
        normal: Fonts.FiraSansRegular,
        italic: Fonts.FiraSansItalic,
      },
      700: {
        normal: Fonts.FiraSansRegular,
        italic: Fonts.FiraSansItalic,
      },
      800: {
        normal: Fonts.FiraSansRegular,
        italic: Fonts.FiraSansItalic,
      },
      900: {
        normal: Fonts.FiraSansRegular,
        italic: Fonts.FiraSansItalic,
      },
    },
  },
  fonts: {
    heading: 'FiraSans',
    body: 'FiraSans',
    mono: 'FiraSans',
  },
  colors: {
    light: {
      buttonText: Colors.White,
      navButtonText: Colors.DeepSpaceSparkle,
      primaryGreen: Colors.GenericViridian,
      primaryBackground: Colors.LightYellow,
      primaryGreenBackground: Colors.pantoneGreen,
      pillText: Colors.MidNightBlack,
      pantoneGreenLight: Colors.pantoneGreenLight,
      // mainBackground: Colors.LightWhite,
      modalGreenBackground: Colors.pantoneGreen,
      modalGreenButton: Colors.pantoneGreen,
      modalGreenSecButtonText: Colors.White,
      modalGreenContent: Colors.White,
      modalWhiteBackground: Colors.LightWhite,
      modalWhiteContent: Colors.GraniteGray,
      modalGreenTitle: Colors.Black,
      modalAccentTitle: Colors.Black,
      modalWhiteButton: Colors.White,
      modalWhiteButtonText: Colors.pantoneGreen,
      modalGreenLearnMore: Colors.CastelGreenDark,
      greenButtonBackground: Colors.pantoneGreen,
      dashedButtonBackground: Colors.lightGreen,
      dashedButtonContent: Colors.White,
      choosePlanHome: Colors.White,
      choosePlanCard: Colors.Seashell,
      choosePlanInactiveText: Colors.Black,
      choosePlanIconBackSelected: Colors.DeepOlive,
      choosePlanIconBack: Colors.PaleKhaki,
      hexagonIconBackColor: Colors.deepTeal,
      qrBorderColor: Colors.White,
      receiveQrBackground: Colors.LightYellow,
      coffeeBackground: Colors.Coffee,
      yellowButtonBackground: Colors.MacaroniAndCheese,
      yellowButtonTextColor: Colors.Coffee,
      btcLabelBack: Colors.Periwinkle,
      white: Colors.White,
      primaryText: Colors.RichBlack,
      secondaryText: Colors.GraniteGray,
      learnMoreBorder: Colors.Coffee,
      textBlack: Colors.DarkGreen,
      greenText: Colors.RichGreen,
      greenText2: Colors.TropicalRainForest,
      sliderStep: Colors.TropicalRainForestDark,
      greenWhiteText: Colors.pantoneGreen,
      accent: Colors.MacaroniAndCheese,
      lightAccent: Colors.MacaroniAndCheese,
      QrCode: Colors.WhiteCoffee,
      recieverAddress: Colors.DimGray,
      textInputBackground: Colors.Isabelline,
      secondaryBackground: Colors.Isabelline,
      GreyText: Colors.Feldgrau,
      dateText: Colors.HookerGreen,
      Border: Colors.CastletonGreen,
      textColor: Colors.LightGray,
      textColor2: Colors.DeepSpaceSparkle,
      headerText: Colors.pantoneGreen,
      copyBackground: Colors.LightGray,
      sendCardHeading: Colors.BlueGreen,
      // Glass: Colors.Glass,
      TorLable: Colors.Menthol,
      divider: Colors.GrayX11,
      errorRed: Colors.CarmineRed,
      SlateGreen: Colors.SlateGreen,
      textWallet: Colors.MediumJungleGreen,
      indicator: Colors.OutrageousOrange,
      addTransactionText: Colors.PineTree,
      sendMax: Colors.JackoBean,
      inActiveMsg: Colors.RichBlack,
      vaultCardText: Colors.Bisque,
      walletTypePillBack: Colors.Bisque,
      pillPlaceholderBack: Colors.LightKhaki,
      satsDark: Colors.DeepSpaceGreen,
      gradientStart: Colors.GenericViridian, // linearGradient
      gradientEnd: Colors.RichGreen, // linearGradient
      error: Colors.CongoPink,
      LightGreenish: Colors.LightGreenish,
      black: Colors.Black,
      fadedGray: Colors.FadedGray,
      fadedblue: Colors.FadeBlue,
      dustySageGreen: Colors.DustySageGreen,
      forestGreen: Colors.ForestGreen,
      pantoneGreen: Colors.pantoneGreen,
      seashellWhite: Colors.Seashell,
      seashellWhiteText: Colors.Seashell,
      lightSeashell: Colors.lightSeashell,
      // Champagne: Colors.Champagne,
      BrownNeedHelp: Colors.RussetBrown,
      policySubtitle: Colors.GreenishGrey,
      balanceText: Colors.GreenishGrey,
      GreenishGrey: Colors.GreenishGrey,
      // Ivory: Colors.Ivory,
      RecoveryBorderColor: Colors.RussetBrownLight,
      brownColor: Colors.brownColor,
      learMoreTextcolor: Colors.learMoreTextcolor,
      // Linen: Colors.Linen,
      whiteText: Colors.OffWhite,
      // SageGreen: Colors.SageGreen,
      TransactionIconBackColor: Colors.Eggshell,
      Teal: Colors.Teal,
      LightBrown: Colors.LightBrown,
      SignleSigCardPillBackColor: Colors.PaleTurquoise,
      DullGreenDark: Colors.DullGreenDark,
      dropdownSeparator: Colors.Taupe,
      LightGreen: Colors.lightGreen,
      lightPurple: Colors.LightPurple,
      MintWhisper: Colors.MintWhisper,
      SlateGrey: Colors.SlateGrey,
      // LightKhaki: Colors.LightKhaki,
      // SmokeGreen: Colors.SmokeGreen,
      // Warmbeige: Colors.Warmbeige,
      // PearlWhite: Colors.PearlWhite,
      // PaleIvory: Colors.PaleIvory,
      DarkSage: Colors.DarkSage,
      // Smoke: Colors.Smoke,
      // deepTeal: Colors.deepTeal,
      ChampagneBliss: Colors.ChampagneBliss,
      // PearlGrey: Colors.PearlGrey,
      // Taupe: Colors.Taupe,
      // Crayola: Colors.Crayola,
      signerCardPill: Colors.Purple,
      dullGreen: Colors.DullGreen,
      darkGrey: Colors.DarkGrey,
      lightSkin: Colors.LightSkin,
      PretitleColor: Colors.LightGreenish,
      disabledColor: Colors.disabledGrey,
      feeInfoTitleColor: Colors.SlateGrey,
      feeInfoColor: Colors.RichBlack,
      greyBorder: Colors.SilverMist,
      placeHolderTextColor: Colors.Graphite,
      linkPreviewBackground: Colors.SeaShellBeige,
      greyBorderTransparent: Colors.SilverMistTransparent,
      limeText: Colors.LimeYellow,
      greenText: Colors.SeaweedGreen,
      greenTextDisabled: Colors.SlateGreen,
      overlayGreen: Colors.pastelGreen,
      alertRedLight: Colors.LightCrimson,
      coralRed: Colors.CoralRed,
      secondaryGrey: Colors.MediumGrey,
      greenPillBackground: Colors.SmokeGreen,
      labelText: Colors.White,
      textDarkGreen: Colors.DarkGreen,
      labelColor1: Colors.LabelLight1,
      labelColor2: Colors.LabelLight2,
      labelColor3: Colors.LabelLight3,
      boxBackground: Colors.BoxGolden,
      borderBrown: Colors.brownColor,
      separator: Colors.separator,
      alertRed: Colors.AlertRed,
      newBadgeGreen: Colors.NewBadgeGreen,
      textGreen: Colors.pantoneGreen,
      textWhite: Colors.Seashell,
      textGreenGrey: Colors.GreenishGrey,
      seedCard: Colors.LightYellow,
      secondaryBackground: Colors.Seashell,
      errorToastBackground: Colors.ErrorToast,
    },
    dark: {
      navButtonText: Colors.SecondaryWhite,
      buttonText: Colors.SecondaryWhite,
      primaryGreen: Colors.GenericViridian,
      darkGrey: Colors.DarkGrey,
      primaryBackground: Colors.PrimaryBlack,
      pillText: Colors.MidNightBlack,
      primaryGreenBackground: Colors.SecondaryBlack,
      pantoneGreenLight: Colors.pantoneGreenLight,
      // mainBackground: Colors.LightWhite,
      modalGreenBackground: Colors.PrimaryBlack,
      modalGreenButton: Colors.DullGreenDark,
      modalGreenSecButtonText: Colors.RichGreenDark,
      modalGreenContent: Colors.White,
      modalWhiteBackground: Colors.ModalBlack,
      modalWhiteContent: Colors.White,
      modalWhiteButton: Colors.DullGreenDark,
      modalWhiteButtonText: Colors.SecondaryWhite,
      modalGreenTitle: Colors.SecondaryWhite,
      modalAccentTitle: Colors.GoldCrayola,
      dullGreen: Colors.DullGreen,
      // modalWhiteButton: Colors.DullGreenDark,
      modalGreenLearnMore: Colors.PrimaryBlack,
      lightPurple: Colors.LightPurple,
      greenButtonBackground: Colors.DullGreenDark,
      dashedButtonBackground: Colors.DullGreenDark,
      dashedButtonContent: Colors.SecondaryWhite,
      choosePlanHome: Colors.White,
      choosePlanCard: Colors.SecondaryBlack,
      choosePlanInactiveText: Colors.SecondaryWhite,
      choosePlanIconBackSelected: Colors.DeepOlive,
      choosePlanIconBack: Colors.GraphiteLight,
      hexagonIconBackColor: Colors.deepTeal,
      qrBorderColor: Colors.White,
      receiveQrBackground: Colors.White,
      coffeeBackground: Colors.CoffeeDark,
      yellowButtonBackground: Colors.PrimaryBlack,
      yellowButtonTextColor: Colors.White,
      btcLabelBack: Colors.Periwinkle,
      white: Colors.SecondaryBlack,
      primaryText: Colors.SecondaryWhite,
      secondaryText: Colors.SecondaryWhite,
      learnMoreBorder: Colors.SecondaryWhite,
      textBlack: Colors.SecondaryWhite,
      greenText: Colors.RichGreenDark,
      greenText2: Colors.TropicalRainForestDark,
      sliderStep: Colors.TropicalRainForestDark,
      greenWhiteText: Colors.White,
      accent: Colors.MacaroniAndCheeseDark,
      lightAccent: Colors.GoldCrayola,
      QrCode: Colors.WhiteCoffee,
      recieverAddress: Colors.DimGray,
      textInputBackground: Colors.Isabelline,
      secondaryBackground: Colors.PrimaryBlack,
      GreyText: Colors.SecondaryWhite,
      dateText: Colors.SecondaryWhite,
      Border: Colors.CastletonGreen,
      textColor: Colors.LightGray,
      textColor2: Colors.DeepSpaceSparkleDark,
      headerText: Colors.SecondaryWhite,
      copyBackground: Colors.LightGray,
      sendCardHeading: Colors.BlueGreen,
      // Glass: Colors.Glass,
      SlateGreen: Colors.SlateGreen,
      TorLable: Colors.Menthol,
      divider: Colors.GrayX11,
      errorRed: Colors.CarmineRed,
      textWallet: Colors.MediumJungleGreen,
      indicator: Colors.OutrageousOrange,
      addTransactionText: Colors.PineTree,
      sendMax: Colors.JackoBean,
      inActiveMsg: Colors.SpanishGray,
      vaultCardText: Colors.Bisque,
      walletTypePillBack: Colors.BisqueDark,
      pillPlaceholderBack: Colors.BisqueDark,
      satsDark: Colors.DeepSpaceGreen,
      gradientStart: Colors.GenericViridian, // linearGradient
      gradientEnd: Colors.DeepAquamarine, // linearGradient
      error: Colors.CongoPink,
      black: Colors.White,
      fadedGray: Colors.SecondaryWhite,
      fadedblue: Colors.FadeBlue,
      dustySageGreen: Colors.DustySageGreen,
      forestGreen: Colors.ForestGreen,
      pantoneGreen: Colors.DullGreenDark,
      seashellWhite: Colors.SeashellDark,
      seashellWhiteText: Colors.SecondaryWhite,
      lightSeashell: Colors.lightSeashell,
      BrownNeedHelp: Colors.RussetBrown,
      policySubtitle: Colors.SecondaryWhite,
      balanceText: Colors.White,
      GreenishGrey: Colors.GreenishGrey,
      RecoveryBorderColor: Colors.RussetBrownLight,
      brownColor: Colors.brownColor,
      learMoreTextcolor: Colors.learMoreTextcolor,
      // Linen: Colors.Linen,
      whiteText: Colors.OffWhite,
      // SageGreen: Colors.SageGreen,
      TransactionIconBackColor: Colors.Eggshell,
      Teal: Colors.Teal,
      LightBrown: Colors.LightBrown,
      SignleSigCardPillBackColor: Colors.Turquoise,
      DullGreenDark: Colors.DullGreenDark,
      dropdownSeparator: Colors.Taupe,
      LightGreen: Colors.lightGreen,
      MintWhisper: Colors.MintWhisper,
      lightSkin: Colors.DarkSkin,
      // SlateGrey: Colors.SlateGrey,
      // LightKhaki: Colors.LightKhaki,
      // SmokeGreen: Colors.SmokeGreen,
      // DeepOlive: Colors.DeepOlive,
      // PaleKhaki: Colors.PaleKhaki,
      // Warmbeige: Colors.Warmbeige,
      // PearlWhite: Colors.PearlWhite,
      // PaleIvory: Colors.PaleIvory,
      DarkSage: Colors.DarkSage,
      // Smoke: Colors.Smoke,
      // deepTeal: Colors.deepTeal,
      // Champagne: Colors.Champagne,
      // Ivory: Colors.Ivory,
      ChampagneBliss: Colors.pantoneGreenLight,
      // PearlGrey: Colors.PearlGrey,
      // Taupe: Colors.Taupe,
      // Crayola: Colors.Crayola,
      signerCardPill: Colors.Purple,
      PretitleColor: Colors.RichBlackDark,
      disabledColor: Colors.disabledGrey,
      feeInfoTitleColor: Colors.White,
      feeInfoColor: Colors.White,
      greyBorder: Colors.SilverMist,
      greyBorderTransparent: Colors.SilverMistTransparent,
      placeHolderTextColor: Colors.GraphiteLight,
      linkPreviewBackground: Colors.GraphiteLight,
      limeText: Colors.LimeYellow,
      greenText: Colors.SecondaryWhite,
      greenTextDisabled: Colors.SlateGreen,
      overlayGreen: Colors.SeashellDark,
      alertRedLight: Colors.LightCrimson,
      coralRed: Colors.CoralRed,
      secondaryGrey: Colors.MediumGrey,
      greenPillBackground: Colors.SmokeGreen,
      labelText: Colors.White,
      textDarkGreen: Colors.White,
      labelColor1: Colors.LabelDark1,
      labelColor2: Colors.LabelDark2,
      labelColor3: Colors.LabelDark3,
      boxBackground: Colors.SecondaryBackgroundDark,
      borderBrown: Colors.SilverMistTransparent,
      separator: Colors.separator,
      alertRed: Colors.AlertRedDark,
      newBadgeGreen: Colors.NewBadgeGreenDark,
      textGreen: Colors.SecondaryWhite,
      textWhite: Colors.SecondaryWhite,
      textGreenGrey: Colors.SecondaryWhite,
      seedCard: Colors.SeashellDark,
      secondaryBackground: Colors.SecondaryBlack,
      errorToastBackground: Colors.ErrorToastDark,
    },
  },
  config: {
    initialColorMode: 'light',
  },
});

export default customTheme;
