export enum TransferType {
  VAULT_TO_WALLET = 'VAULT_TO_WALLET',
  VAULT_TO_VAULT = 'VAULT_TO_VAULT',
  WALLET_TO_WALLET = 'WALLET_TO_WALLET',
  WALLET_TO_VAULT = 'WALLET_TO_VAULT',
  WALLET_TO_ADDRESS = 'WALLET_TO_ADDRESS',
  VAULT_TO_ADDRESS = 'VAULT_TO_ADDRESS',
}
