export const COLDCARD_EXPORT = {
  data: {
    account: 13,
    bip44: {
      deriv: "m/44'/1'/13'",
      first: 'mniHcs7yEgqVJ6D3YUV6g6Y4HtTzMo7kHM',
      name: 'p2pkh',
      xfp: '3938DFB4',
      xpub: 'tpubDC9LihH2FxGQaUPyer4K7vn53tTawMZidZ5Uqfn2hLGpB8MVSyPVz2h1EAJycLv3PnBWVRg2bCTEM5fgfHnFthPokCSpzoYscwo9tqb4iwa',
    },
    bip48_1: {
      _pub: 'Upub5Sk2WcfjmoG5aSTr2L5qnuu9Kfnthn4h5wKiTrKMS8cTwZLq9pWtQ7mJFmNqULmbS5PE2WtrpafoKq9FMTv8i6tiRG8qgBiNC61MERtcn4f',
      deriv: "m/48'/1'/13'/1'",
      name: 'p2sh-p2wsh',
      xfp: 'CD4AFC61',
      xpub: 'tpubDEiMpcmjNAHbyZ4g2vxpo2BDSuHdJfrf4dq1FKncYHfbDxtKDcUPKdYckiNuS8ThDSCa1wCHrTAzYhrncBrTqmH9FQs1i3N4hVWpaDXQSoP',
    },
    bip48_2: {
      _pub: 'Vpub5maHpHLevUoZUoC6wGMgsZfgSPCwgc1a4P12TLtEYMJPguBPiFNFmJHtr8RTqLcUsQvNbwQRoZQQnJ3EDv3NpBo4yBXSHri9eiqxZXsAq7C',
      deriv: "m/48'/1'/13'/2'",
      name: 'p2wsh',
      xfp: '299B6A14',
      xpub: 'tpubDEiMpcmjNAHc2cbp7WT3farFPeZELsp37xz6TRTcGVydvCueXPAC4kR5KsTwoDefF8cuqt7JNmZ47t9CkwZh9cVtvzZBjoYMtQHnWjqtJae',
    },
    bip49: {
      _pub: 'upub5DgUm7PTrXRUWdLXaMg7uRKqwoVbSYjAP7QP4STEgjBYdoD5MGKgHf18UqXggdgcxYLe785NviymaqdvD3EzX2STG6aZRhaFAx4qoKrgyis',
      deriv: "m/49'/1'/13'",
      first: '2NEZQnS6osvnCJ2Vo295wWiAimB6t4bYLfY',
      name: 'p2sh-p2wpkh',
      xfp: '22386C3B',
      xpub: 'tpubDCYuCMDu1r1NLK6jXd25jbwinq2bFoCig5ZLmBC3Af55YPKUBTfTJHeNnVVECrbcyNDxy8NvqosTvsyDkzLGoAwYviR8rxgwa5rBj9AT4Ct',
    },
    bip84: {
      _pub: 'vpub5ZDk9mRXaiWmRfy3GRUPWXwtAVAuwUX8iSf4AYvMBywCGJzsVew4xopmy87ZJURcpvz7U8yK4PnwY6EdHhLFqhzh24ud3zzDbJJEop5v42g',
      deriv: "m/84'/1'/13'",
      first: 'tb1qclvfyg5v9gahygk5la56afevcnpdxt203609gp',
      name: 'p2wpkh',
      xfp: 'ED0DF249',
      xpub: 'tpubDDFuHLb3bMZBQ4Y8PL2j8dUFqYZTp71C6JHo5tmGHuSr7oJ35C7HMNotFa7WpnghS7kdafgJWpL5zqxN7x1XKcpBpM3muMHRii1wLvCKoYT',
    },
    chain: 'XTN',
    xfp: 'B47CF9C5',
    xpub: 'xpub661MyMwAqRbcFJ7KPwUrnNTRMcfDqgNuuq5zmJ9AJKe8v9iSVVttsh2vgJKCSJqoZSuGM5KVzQ6Nc7utgwq64UzhsX3B6Mm6CcvTEEDdipF',
  },
  rtdName: 'application/json',
};

export const SEEDSIGNER_SS_EXPORT = {
  data: "[e1e66310/84'/1'/0']vpub5Yaq4u2kgKTnHrv67VHj8FswPcZu3K42rUhXk59kcZuTnDQDkwks19kT5jmpdtseQN9y63tiFvGPcas8AH7wBPG6nxEbG7TP5Kp269gdV87",
};

export const SEEDSIGNER_MS_EXPORT = {
  data: "[e1e66310/48'/1'/0'/2']Vpub5mi6ECWJzhCyi7Vzjuu2SDectGsP8jK45sC6mspyQvw5FiHaHWPhPmhng2jdyfAmk423kMnffFP1iaSM6ZN8yS9EZdJnMJPBZj1Rb1r8QfY",
};

export const KEYSTONE_SS_EXPORT = {
  data: 'UR:CRYPTO-ACCOUNT/OEADCYHSROZTSSAOLYTAADMWTAADDLOSAOWKAXHDCLAOCAJTGTMTWMWENSNYRHGUCFFTVAZTWKMSAMFWLTCKOECKKPBSFYJPDIVAGDBWRTAAAAHDCXLTDTFYHFLPINBNIABDENLNVLWKRTCYYTDRIMBEMYOEOYZSETDPKENEDAWTTKNEDPAHTAADEHOEADADAOADAMTAADDYOTADLNCSGHYKADYKAEYKAOCYHSROZTSSAXAXATTAADDYOEADLRAEWKLAWKAXAEAYCYBTLYAEWDFTKBHTFX',
};

export const KEYSTONE_MS_EXPORT = {
  data: 'UR:CRYPTO-ACCOUNT/OEADCYHSROZTSSAOLYTAADMETAADDLOLAOWKAXHDCLAOMTCYTTCWATUOFDZCGWNNJNFNVSMSSFUELKKSUELTAYSRNDMYTODYVSWLKEVEVDTKAAHDCXUESKRSRDMODLGYTLJLFRCTDKDWSNKTDKMWMHTLJEGWDKKGHYVOASMKWDLBRSPSMSAHTAADEHOEADADAOADAMTAADDYOTADLOCSDYYKADYKAEYKAOYKAOCYHSROZTSSAXAAAYCYSOECMTBZUYREHFCE',
};

export const PASSPORT_SS_EXPORT = [
  {
    data: 'UR:BYTES/82-14/LPCSGMBACFATDYCYGYTIIAJKHDLRBSFDAEFMJPKEBWGUDLAODIGRCHATFWCADWCPJTFMFGFDDLBBCWKBGLCLGTFZHPCNKSFWDTAAEOGMJKGYCYCNGTKOFDCFINCWGHDLFHAMJNGDGEJLGSDSCNAAAMENDPGACXIOIDIYGSGEBECKFHJLEHINBEAAHPCHIECEFXCSCFCEASFWDPADKSCKJSJZIOAOFZHEJLGOFSBSFEFTIADKGTJKJLGOJEENFNKSETFLGABKIAHKKOCSINGUCMIAJOJEDTCTHPIHBGLKYNLD',
  },
  {
    data: 'UR:BYTES/83-14/LPCSGUBACFATDYCYGYTIIAJKHDLRKIDWCXCPIDINJOEEEECPFTCXKGCPKSJOKPIDCPFTCXCPJYJOKPIDFYFXIDKSGEKSKNGUHFGOKPETKPHDFYJLEEKPECHKGRFGGMJEETFGIAINECFEFWKPGDGEJNHKGOKSGMEMIAJOJKINEHEEIOGEISGMFEGOFPHDGTIEIEJLJNJTIHGHHTJOJYHGGOGREEFDKTECISGOHKHDGRGEGRGYGRKPKNGEHDHGGOIEIAHDFYGREEEOHDGLIOKNGEKOEHHDINGOIAHSJTMDINSE',
  },
];

export const PASSPORT_MS_EXPORT = [
  {
    data: 'UR:BYTES/9-4/LPASAACFADZCCYWZMYHFWYHDLAEMIOLKCAKIGHFGHSBYIAFZHHCSBNCXFNHDEHIEBNGAFZCXISCMCFDPAOBNDEGDBGGOAXHTDWCSBEGAFDKIBEBZATBDEYCYHKBWGUDACFIAASJKCHAEJYKGAOKIGLGAGMISKIIDJKIDKSCWGDCTBYBGIYGAGEDNASGMASFPGMAEBBFRDKATBEBWAXCEASHSHHECBZDMCACPEOBWHPAEDNAODSBNAXCPEMFHJECPAEDKASDSCKIHGRBSDEASDWAYCKATLDNBJO',
  },
  {
    data: 'UR:BYTES/10-4/LPBKAACFADZCCYWZMYHFWYHDLACMJYRLENKGGWJSGTAHKSFZIOHHDEDYCPFLDRISGDFTIYCNHYAOCNISKEBTIHHEGLHFDWCFGODPEHBABBFHAHCLCLAYEHCWFXHEFXBNESJLBZKNFNCHIHCWCYASKNKGDALBHLJTBWEMCFAXDRIOBEKOKBJTBWBWCWIDECGSKOFXCYJYECGMGRGSGLINKTETENHGGMIEIYEYETFRHGDRDTHTIDBNBWJLIEKPKGHLIDFYJZBZDEEMHHJEIADYIEFRDTHLCMLDBB',
  },
];

export const JADE_SS_EXPORT = [
  {
    data: 'UR:CRYPTO-ACCOUNT/1-5/LPADAHCSJKCYZTHDCLGSHGOEADCYYNCTECJOAOLYTAADMWTAADDLOXAXHDCLAXCNLRVTWYPADPYK',
  },
  {
    data: 'UR:CRYPTO-ACCOUNT/2-5/LPAOAHCSJKCYZTHDCLGSHGASZTTDWZRNLOGRHGQDRTJYNSDELDINRTJOJSNLKEFLKOKIBKJEVWKS',
  },
];

export const JADE_MS_EXPORT = [
  {
    data: 'UR:CRYPTO-ACCOUNT/1-6/LPADAMCSKPCYVEDNCMURGHOEADCYYNCTECJOAOLYTAADMETAADDLOXAXHDCLAXVETYVEDT',
  },
  {
    data: 'UR:CRYPTO-ACCOUNT/2-6/LPAOAMCSKPCYVEDNCMURGHMSEMFEYLTKMNSNKIVSZSTOSPESVAVSCSONSOKNDTLYJEZCCK',
  },
];

export const SPECTER_SS_EXPORT = {
  data: `[7b3dbb45/84h/1h/0h]vpub5Ys6SfiqrjcFR2QUMtmcm8t59ZCCHw3TR6vb6vMAmCo92L7ftMGE4iMyC91eci2LCJKaypT4ErJc3ygcBh7Zq2K81JZKQRwdu8orSkZHzro`,
};

export const SPECTER_MS_EXPORT = {
  data: `[7b3dbb45/48h/1h/0h/2h]Vpub5nePDyjmt4kxv41wS2NmY2Gz7nadNvnxVqAuCNaaBFtxafXp34MPY9VqUFPHXuWafdxQKPwpNDPAYgaAVoZyQ12CDU2AP8eaAkz5V6MUrps`,
};

export const MOBILE_KEY_EXPORT =
  'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about';

export const KEEPER_EXTERNAL_EXPORT = {
  data: '[8FDFB83F/48h/1h/0h/2h]tpubDELcPFbwvZvAQ7PGitsvHLRTgfYZ2TZ83ftYwxbDaxaq3MmpzHZkYB5XWv5EcvuvKvYsyvcPC44VBz2vSyQXSdonrjiQr7BMNLcNL5Rrs73',
};

export const KEEPER_INTERNAL_EXPORT =
  'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about';

export const SEED_WORDS_EXPORT =
  'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about';
